# Generated by Django 5.2.8 on 2025-11-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Headline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=350)),
                ("url", models.URLField(unique=True)),
                ("source", models.CharField(default="Unknown", max_length=50)),
            ],
        ),
    ]
